### ISSUE TITLE
updates in the dependancy stack

### ISSUE THREAD

**Issue by shimwell** [Hazunanafaru/iter-tritium-breeding-xgboost#1]
Hi @Hazunanafaru 

We noticed you are making good use of a few codes and just wanted to mention a few updates we have planned in the future. ```paramak_neutronics``` has now been discontinued and is being replaced by ```openmc-dagmc-wrapper```.

the first usable version of ```openmc-dagmc-wrapper``` is still a about a week away as we are currently just refactoring it.

**Comment by shimwell** [comment]
You might also be interested in https://github.com/fusion-energy/openmc-plasma-source/

**Comment by husni-zuhdi** [comment]
Thank you for letting me know @shimwell. I'll upgrade to openmc-dagmc-wrapper after tidy up this repository.

**Comment by Hazunanafaru** [comment]
Thank you for letting me know @shimwell. I'll upgrade to openmc-dagmc-wrapper after tidying up this repository.
